[package]
name = "npcli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
boilerplate = "1.0.0"
cargo_metadata = "0.18.1"
clap = { version = "4.5.8", features = ["derive"] }
cliclack = "0.3.1"
nih_plug_xtask = { path = "./nih_plug_xtask/" }
